.TH TAPETYPE 1
.SH NAME
tapetype \- test a tape in a tape drive and generate an Amanda tapetype entry
.SH SYNOPSIS
.B tapetype
.SH "DESCRIPTION"
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.

.SH AUTHOR
This manual page was written by Bdale Garbee <bdale@gag.com>,
for the Debian GNU/Linux system (but may be used by others).
